# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a36f46b986f71e6aa0f901088d74a459b40c9ddd627c2f115a8d985b642e2ee8fcfcaf2ba2b2dc7327f19f7415b0ffcd8c22ba2767a3c585a76af83d11cd7b2

test:
  secret_key_base: 7671fb1233541f9093801de73417e86bec6714ed9fa81220c4c1171b019003dca59ff821b3650ec0d8ff7183bb5ca2b02e506eba5d2f1989d22d3ece3740728a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
